In [1]:
import numpy as np

In [ ]:
#Mi ejemplo
import math as m

In [ ]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [2]:
#Mi ejemplo
lis=[1,2,3,4,5]
pa=np.array(lis)
print(pa,type(pa))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
Ar = np.array([[1,3],[2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [5]:
#Mi ejemplo
AR = np.array([[1,3],[2,4]])
print(AR, type(AR))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [ ]:
print(Ar.shape)

(2, 2)


In [6]:
#Mi ejemplo
print(AR.shape)

(2, 2)


In [ ]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [7]:
#Mi ejemplo
print(AR[0])
print(AR[1])

[1 3]
[2 4]


In [ ]:
print('the first column: ', Ar[:,0])
print('the second column: ', Ar[:,1])

the first column:  [1 2]
the second column:  [3 4]


In [8]:
#Mi ejemplo
print('primera columna: ', AR[:,0])
print('segunda columna: ', AR[:,1])

primera columna:  [1 2]
segunda columna:  [3 4]


In [ ]:
print(np.log(price_array))

[ 4.96793654  4.98244156  4.9675886   4.96995218  4.96633504  4.96018375]


In [9]:
#Mi ejemplo
print(np.log(pa))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


In [10]:
#Mi ejemplo
print(np.mean(pa))
print(np.std(pa))
print(np.sum(pa))
print(np.max(pa))

3.0
1.4142135623730951
15
5


In [ ]:
import pandas as pd

In [ ]:
#Mi ejemplo
import cmat as cm

In [ ]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
s

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64

In [12]:
#Mi ejemplo
import pandas as pd

pri = [1.1, 2.2, 3.3, 4.4, 5.5, 6.6]
se = pd.Series(pri)
se

0    1.1
1    2.2
2    3.3
3    4.4
4    5.5
5    6.6
dtype: float64

In [ ]:
s = pd.Series(price,index = ['a','b','c','d','e','f'])
s

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64

In [14]:
#Mi ejemplo
se = pd.Series(pri,index = ['a','b','c','d','e','f'])
se

a    1.1
b    2.2
c    3.3
d    4.4
e    5.5
f    6.6
dtype: float64

In [ ]:
s.index = [6,5,4,3,2,1]
s

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64

In [15]:
#Mi ejemplo
se.index = [6,5,4,3,2,1]
se

6    1.1
5    2.2
4    3.3
3    4.4
2    5.5
1    6.6
dtype: float64

In [16]:
print(s[1:])
print(s[:-2])

5    2.2
4    3.3
3    4.4
2    5.5
1    6.6
dtype: float64
6    1.1
5    2.2
4    3.3
3    4.4
dtype: float64


In [18]:
#Mi ejemplo
print(se[1:])
print(se[:-2])

5    2.2
4    3.3
3    4.4
2    5.5
1    6.6
dtype: float64
6    1.1
5    2.2
4    3.3
3    4.4
dtype: float64


In [ ]:
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [19]:
#Mi ejemplo
print(se[4])
se[4] = 0
print(se)

3.3
6    1.1
5    2.2
4    0.0
3    4.4
2    5.5
1    6.6
dtype: float64


In [ ]:
s = pd.Series(price, name = 'Apple Price List')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Price List, dtype: float64
Apple Price List


In [20]:
#Mi ejemplo
se = pd.Series(pri, name = 'tesla')
print(se)
print(se.name)

0    1.1
1    2.2
2    3.3
3    4.4
4    5.5
5    6.6
Name: tesla, dtype: float64
tesla


In [ ]:
time_index = pd.date_range('2017-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Price List, dtype: float64


In [22]:
#Mi ejemplo
timendex = pd.date_range('2017-01-01',periods = len(se),freq = 'D')
print(timendex)
se.index = timendex
print(se)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    1.1
2017-01-02    2.2
2017-01-03    3.3
2017-01-04    4.4
2017-01-05    5.5
2017-01-06    6.6
Freq: D, Name: tesla, dtype: float64


In [ ]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Price List, dtype: float64
142.62


In [23]:
#Mi ejemplo
se.index = [6,5,4,3,2,1]
print(se)
print(se[1])

6    1.1
5    2.2
4    3.3
3    4.4
2    5.5
1    6.6
Name: tesla, dtype: float64
6.6


In [ ]:
print(s.iloc[1])

145.83


In [24]:
#Mi ejemplo
print(se.iloc[1])

2.2


In [ ]:
s.index = time_index
print(s['2017-01-03'])

143.68


In [26]:
#Mi ejemplo
se.index = timendex
print(se['2017-01-03'])

3.3


In [ ]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Price List, dtype: float64


In [27]:
#Mi ejemplo
print(se['2017-01-02':'2017-01-05'])

2017-01-02    2.2
2017-01-03    3.3
2017-01-04    4.4
2017-01-05    5.5
Freq: D, Name: tesla, dtype: float64


In [ ]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

6    143.73
4    143.68
2    143.50
1    142.62
Name: Apple Price List, dtype: float64
[6    False
5    False
4    False
3     True
2    False
1    False
Name: Apple Price List, dtype: bool]


In [28]:
#Mi ejemplo
print(se[se < np.mean(se)] )
print([(se > np.mean(se)) & (se < np.mean(se) + 1.64*np.std(se))])

2017-01-01    1.1
2017-01-02    2.2
2017-01-03    3.3
Freq: D, Name: tesla, dtype: float64
[2017-01-01    False
2017-01-02    False
2017-01-03    False
2017-01-04     True
2017-01-05     True
2017-01-06     True
Freq: D, Name: tesla, dtype: bool]
